POST http://localhost:3333/events
Content-Type: application/json

{
	"title": 1,
	"details": "null",
	"maximumAttendees": 1
}

###

POST http://localhost:3333/events/d8234c18-37d6-45f3-a631-2cfce28d6b95/attendees
Content-Type: application/json

{
	"name": "Diego Fernandes",
	"email": "diego2@rocketseat.com"
}

###

GET http://localhost:3333/events/d8234c18-37d6-45f3-a631-2cfce28d6b95

###

GET http://localhost:3333/attendees/3/badge

###

GET http://localhost:3333/attendees/5/check-in

###

GET http://localhost:3333/events/d8234c18-37d6-45f3-a631-2cfce28d6b95/attendees?query=diego

###

PUT http://localhost:3333/events/cb0e032a-fd91-440c-8093-34ae7b8566e7
Content-Type: application/json

{
	"title": "Evento atualizado",
	"details": "Um evento atualizado",
	"maximumAttendees": 100
}

###

DELETE http://localhost:3333/events/cb0e032a-fd91-440c-8093-34ae7b8566e7

###
PUT http://localhost:3333/attendees/3
Content-Type: application/json

{
	"name": "Diego Gonçalves",
	"email": "diego.goncalves@rocketseat.com"
}

###

DELETE http://localhost:3333/attendees/3

